# Generated by Django 5.0.6 on 2024-06-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
    ]
