# Generated by Django 5.0.6 on 2024-06-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lectures',
            new_name='lecture',
        ),
    ]
